# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rproxy < Formula
  desc "Runops Proxy forwards remote tcp connections locally."
  homepage "https://github.com/runopsio/rproxy"
  version "0.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runopsio/rproxy/releases/download/0.2.6/rproxy_0.2.6_Darwin_x86_64.tar.gz"
      sha256 "6d5620a2c9d27a46a3abd915a56a3755d92cf6f23d239fb78698e08065464d6d"

      def install
        bin.install "rproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runopsio/rproxy/releases/download/0.2.6/rproxy_0.2.6_Darwin_arm64.tar.gz"
      sha256 "2e5c45c39ee4b5323b3cd02896d963d2ceeae8f566c5e718205520aeaaee7e9c"

      def install
        bin.install "rproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runopsio/rproxy/releases/download/0.2.6/rproxy_0.2.6_Linux_arm64.tar.gz"
      sha256 "a9ed50067641741b9a7284501128cfa880a2c4eac0be93b88ef39ae55d739f7c"

      def install
        bin.install "rproxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runopsio/rproxy/releases/download/0.2.6/rproxy_0.2.6_Linux_x86_64.tar.gz"
      sha256 "c36f4bb5d916b15613fda02b1772e5b8ec6f25997bdb76cb8a80833fcb9efd38"

      def install
        bin.install "rproxy"
      end
    end
  end
end
