# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rproxy < Formula
  desc "Runops Proxy forwards remote tcp connections locally."
  homepage "https://github.com/runopsio/rproxy"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runopsio/rproxy/releases/download/0.1.4/rproxy_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "f8092e2543fcbce44d6a93db111f065ab6ab5f7dbe8ef5c9e1f4922446b77442"

      def install
        bin.install "rproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runopsio/rproxy/releases/download/0.1.4/rproxy_0.1.4_Darwin_arm64.tar.gz"
      sha256 "8b8c52b1a520e9b316a23a8f495d43a7c9209d40953feac3cd68474e9aa3cd41"

      def install
        bin.install "rproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runopsio/rproxy/releases/download/0.1.4/rproxy_0.1.4_Linux_arm64.tar.gz"
      sha256 "4c05690422b6527c3942a70596d70ba27221a36f739b7d0409639312d0d3f66c"

      def install
        bin.install "rproxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/runopsio/rproxy/releases/download/0.1.4/rproxy_0.1.4_Linux_x86_64.tar.gz"
      sha256 "cc9bd0b9911f47d223cc40730ecc2d0081bbaaec5b824bfc54e4e1c028dd0763"

      def install
        bin.install "rproxy"
      end
    end
  end
end
