name: Generate a client release on GitHub/Dockerhub

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    name: Client Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'runopsio/runops-proxy'
          ssh-key: ${{ secrets.GH_SSH_KEY }}
          path: ./rproxy

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.3'

      - name: Docker Login
        run: docker login -u=${{ secrets.DOCKER_LOGIN }} -p=${{ secrets.DOCKER_PASSWORD }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --config .goreleaser.yaml
          workdir: ./rproxy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
